// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type BoolStatus int64

const (
	BoolStatus_TRUE  BoolStatus = 0
	BoolStatus_FALSE BoolStatus = 1
)

func (p BoolStatus) String() string {
	switch p {
	case BoolStatus_TRUE:
		return "TRUE"
	case BoolStatus_FALSE:
		return "FALSE"
	}
	return "<UNSET>"
}

func BoolStatusFromString(s string) (BoolStatus, error) {
	switch s {
	case "TRUE":
		return BoolStatus_TRUE, nil
	case "FALSE":
		return BoolStatus_FALSE, nil
	}
	return BoolStatus(0), fmt.Errorf("not a valid BoolStatus string")
}

func BoolStatusPtr(v BoolStatus) *BoolStatus { return &v }
func (p *BoolStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BoolStatus(result.Int64)
	return
}

func (p *BoolStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BaseResponse struct {
	Code int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResponse) SetCode(val int64) {
	p.Code = val
}
func (p *BaseResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "code",
	2: "msg",
}

type NilResponse struct {
}

func NewNilResponse() *NilResponse {
	return &NilResponse{}
}

func (p *NilResponse) InitDefault() {
}

func (p *NilResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NilResponse(%+v)", *p)
}

var fieldIDToName_NilResponse = map[int16]string{}

type Pager struct {
	Paged     int32 `thrift:"paged,1" frugal:"1,default,i32" json:"paged"`
	Total     int32 `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	PageCount int32 `thrift:"page_count,3" frugal:"3,default,i32" json:"page_count"`
	PageSize  int32 `thrift:"page_size,4" frugal:"4,default,i32" json:"page_size"`
	PrevPage  int32 `thrift:"prev_page,5" frugal:"5,default,i32" json:"prev_page"`
	LastPage  int32 `thrift:"last_page,6" frugal:"6,default,i32" json:"last_page"`
}

func NewPager() *Pager {
	return &Pager{}
}

func (p *Pager) InitDefault() {
}

func (p *Pager) GetPaged() (v int32) {
	return p.Paged
}

func (p *Pager) GetTotal() (v int32) {
	return p.Total
}

func (p *Pager) GetPageCount() (v int32) {
	return p.PageCount
}

func (p *Pager) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *Pager) GetPrevPage() (v int32) {
	return p.PrevPage
}

func (p *Pager) GetLastPage() (v int32) {
	return p.LastPage
}
func (p *Pager) SetPaged(val int32) {
	p.Paged = val
}
func (p *Pager) SetTotal(val int32) {
	p.Total = val
}
func (p *Pager) SetPageCount(val int32) {
	p.PageCount = val
}
func (p *Pager) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *Pager) SetPrevPage(val int32) {
	p.PrevPage = val
}
func (p *Pager) SetLastPage(val int32) {
	p.LastPage = val
}

func (p *Pager) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Pager(%+v)", *p)
}

var fieldIDToName_Pager = map[int16]string{
	1: "paged",
	2: "total",
	3: "page_count",
	4: "page_size",
	5: "prev_page",
	6: "last_page",
}
