// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package errno

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Err int64

const (
	Err_Success            Err = 0
	Err_NoRoute            Err = 1
	Err_NoMethod           Err = 2
	Err_BadRequest         Err = 10000
	Err_ParamsErr          Err = 10001
	Err_AuthorizeFail      Err = 10002
	Err_TooManyRequest     Err = 10003
	Err_ServiceErr         Err = 20000
	Err_RPCTenantSrvErr    Err = 30000
	Err_TenantSrvErr       Err = 30001
	Err_RPCBlobSrvErr      Err = 40000
	Err_BlobSrvErr         Err = 40001
	Err_RPCPowerSrvErr     Err = 50000
	Err_PowerSrvErr        Err = 50001
	Err_RPCSettingSrvErr   Err = 60000
	Err_SettingSrvErr      Err = 60001
	Err_RPCOmsSrvErr       Err = 70000
	Err_OmsSrvErr          Err = 70001
	Err_RecordNotFound     Err = 80000
	Err_RecordAlreadyExist Err = 80001
	Err_DirtyData          Err = 80003
	Err_TradeSrvErr        Err = 90001
)

func (p Err) String() string {
	switch p {
	case Err_Success:
		return "Success"
	case Err_NoRoute:
		return "NoRoute"
	case Err_NoMethod:
		return "NoMethod"
	case Err_BadRequest:
		return "BadRequest"
	case Err_ParamsErr:
		return "ParamsErr"
	case Err_AuthorizeFail:
		return "AuthorizeFail"
	case Err_TooManyRequest:
		return "TooManyRequest"
	case Err_ServiceErr:
		return "ServiceErr"
	case Err_RPCTenantSrvErr:
		return "RPCTenantSrvErr"
	case Err_TenantSrvErr:
		return "TenantSrvErr"
	case Err_RPCBlobSrvErr:
		return "RPCBlobSrvErr"
	case Err_BlobSrvErr:
		return "BlobSrvErr"
	case Err_RPCPowerSrvErr:
		return "RPCPowerSrvErr"
	case Err_PowerSrvErr:
		return "PowerSrvErr"
	case Err_RPCSettingSrvErr:
		return "RPCSettingSrvErr"
	case Err_SettingSrvErr:
		return "SettingSrvErr"
	case Err_RPCOmsSrvErr:
		return "RPCOmsSrvErr"
	case Err_OmsSrvErr:
		return "OmsSrvErr"
	case Err_RecordNotFound:
		return "RecordNotFound"
	case Err_RecordAlreadyExist:
		return "RecordAlreadyExist"
	case Err_DirtyData:
		return "DirtyData"
	case Err_TradeSrvErr:
		return "TradeSrvErr"
	}
	return "<UNSET>"
}

func ErrFromString(s string) (Err, error) {
	switch s {
	case "Success":
		return Err_Success, nil
	case "NoRoute":
		return Err_NoRoute, nil
	case "NoMethod":
		return Err_NoMethod, nil
	case "BadRequest":
		return Err_BadRequest, nil
	case "ParamsErr":
		return Err_ParamsErr, nil
	case "AuthorizeFail":
		return Err_AuthorizeFail, nil
	case "TooManyRequest":
		return Err_TooManyRequest, nil
	case "ServiceErr":
		return Err_ServiceErr, nil
	case "RPCTenantSrvErr":
		return Err_RPCTenantSrvErr, nil
	case "TenantSrvErr":
		return Err_TenantSrvErr, nil
	case "RPCBlobSrvErr":
		return Err_RPCBlobSrvErr, nil
	case "BlobSrvErr":
		return Err_BlobSrvErr, nil
	case "RPCPowerSrvErr":
		return Err_RPCPowerSrvErr, nil
	case "PowerSrvErr":
		return Err_PowerSrvErr, nil
	case "RPCSettingSrvErr":
		return Err_RPCSettingSrvErr, nil
	case "SettingSrvErr":
		return Err_SettingSrvErr, nil
	case "RPCOmsSrvErr":
		return Err_RPCOmsSrvErr, nil
	case "OmsSrvErr":
		return Err_OmsSrvErr, nil
	case "RecordNotFound":
		return Err_RecordNotFound, nil
	case "RecordAlreadyExist":
		return Err_RecordAlreadyExist, nil
	case "DirtyData":
		return Err_DirtyData, nil
	case "TradeSrvErr":
		return Err_TradeSrvErr, nil
	}
	return Err(0), fmt.Errorf("not a valid Err string")
}

func ErrPtr(v Err) *Err { return &v }
func (p *Err) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Err(result.Int64)
	return
}

func (p *Err) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
