// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package errno

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Err int64

const (
	Err_Success                Err = 0
	Err_NoRoute                Err = 1
	Err_NoMethod               Err = 2
	Err_TokenErr               Err = 10000
	Err_BadRequest             Err = 20000
	Err_ParamsErr              Err = 20001
	Err_AuthorizeFail          Err = 20002
	Err_TooManyRequest         Err = 20003
	Err_ServiceErr             Err = 20004
	Err_RecordNotFound         Err = 30000
	Err_RecordAlreadyExist     Err = 30001
	Err_DirtyData              Err = 30002
	Err_ApiServiceErr          Err = 40000
	Err_GlobalSrvClientErr     Err = 41000
	Err_ComTenantSrvErr        Err = 50000
	Err_ComTenantSrvClientErr  Err = 50001
	Err_ComSettingSrvErr       Err = 51000
	Err_ComSettingSrvClientErr Err = 51001
	Err_SysPowerSrvErr         Err = 60000
	Err_SysPowerSrvClientErr   Err = 60001
	Err_SysBlobSrvErr          Err = 61000
	Err_SysBlobSrvClientErr    Err = 61001
	Err_SysSiteSrvErr          Err = 62000
	Err_SysSiteSrvClientErr    Err = 62001
	Err_BuyCrmSrvErr           Err = 70000
	Err_BuyCrmSrvClientErr     Err = 70001
	Err_BuyOmsSrvErr           Err = 71000
	Err_BuyOmsSrvClientErr     Err = 71001
	Err_BuyPaySrvErr           Err = 72000
	Err_BuyPaySrvClientErr     Err = 72001
	Err_BuyPdmSrvErr           Err = 73000
	Err_BuyPdmSrvClientErr     Err = 73001
	Err_KitAigcSrvErr          Err = 80000
	Err_KitAigcSrvClientErr    Err = 80001
)

func (p Err) String() string {
	switch p {
	case Err_Success:
		return "Success"
	case Err_NoRoute:
		return "NoRoute"
	case Err_NoMethod:
		return "NoMethod"
	case Err_TokenErr:
		return "TokenErr"
	case Err_BadRequest:
		return "BadRequest"
	case Err_ParamsErr:
		return "ParamsErr"
	case Err_AuthorizeFail:
		return "AuthorizeFail"
	case Err_TooManyRequest:
		return "TooManyRequest"
	case Err_ServiceErr:
		return "ServiceErr"
	case Err_RecordNotFound:
		return "RecordNotFound"
	case Err_RecordAlreadyExist:
		return "RecordAlreadyExist"
	case Err_DirtyData:
		return "DirtyData"
	case Err_ApiServiceErr:
		return "ApiServiceErr"
	case Err_GlobalSrvClientErr:
		return "GlobalSrvClientErr"
	case Err_ComTenantSrvErr:
		return "ComTenantSrvErr"
	case Err_ComTenantSrvClientErr:
		return "ComTenantSrvClientErr"
	case Err_ComSettingSrvErr:
		return "ComSettingSrvErr"
	case Err_ComSettingSrvClientErr:
		return "ComSettingSrvClientErr"
	case Err_SysPowerSrvErr:
		return "SysPowerSrvErr"
	case Err_SysPowerSrvClientErr:
		return "SysPowerSrvClientErr"
	case Err_SysBlobSrvErr:
		return "SysBlobSrvErr"
	case Err_SysBlobSrvClientErr:
		return "SysBlobSrvClientErr"
	case Err_SysSiteSrvErr:
		return "SysSiteSrvErr"
	case Err_SysSiteSrvClientErr:
		return "SysSiteSrvClientErr"
	case Err_BuyCrmSrvErr:
		return "BuyCrmSrvErr"
	case Err_BuyCrmSrvClientErr:
		return "BuyCrmSrvClientErr"
	case Err_BuyOmsSrvErr:
		return "BuyOmsSrvErr"
	case Err_BuyOmsSrvClientErr:
		return "BuyOmsSrvClientErr"
	case Err_BuyPaySrvErr:
		return "BuyPaySrvErr"
	case Err_BuyPaySrvClientErr:
		return "BuyPaySrvClientErr"
	case Err_BuyPdmSrvErr:
		return "BuyPdmSrvErr"
	case Err_BuyPdmSrvClientErr:
		return "BuyPdmSrvClientErr"
	case Err_KitAigcSrvErr:
		return "KitAigcSrvErr"
	case Err_KitAigcSrvClientErr:
		return "KitAigcSrvClientErr"
	}
	return "<UNSET>"
}

func ErrFromString(s string) (Err, error) {
	switch s {
	case "Success":
		return Err_Success, nil
	case "NoRoute":
		return Err_NoRoute, nil
	case "NoMethod":
		return Err_NoMethod, nil
	case "TokenErr":
		return Err_TokenErr, nil
	case "BadRequest":
		return Err_BadRequest, nil
	case "ParamsErr":
		return Err_ParamsErr, nil
	case "AuthorizeFail":
		return Err_AuthorizeFail, nil
	case "TooManyRequest":
		return Err_TooManyRequest, nil
	case "ServiceErr":
		return Err_ServiceErr, nil
	case "RecordNotFound":
		return Err_RecordNotFound, nil
	case "RecordAlreadyExist":
		return Err_RecordAlreadyExist, nil
	case "DirtyData":
		return Err_DirtyData, nil
	case "ApiServiceErr":
		return Err_ApiServiceErr, nil
	case "GlobalSrvClientErr":
		return Err_GlobalSrvClientErr, nil
	case "ComTenantSrvErr":
		return Err_ComTenantSrvErr, nil
	case "ComTenantSrvClientErr":
		return Err_ComTenantSrvClientErr, nil
	case "ComSettingSrvErr":
		return Err_ComSettingSrvErr, nil
	case "ComSettingSrvClientErr":
		return Err_ComSettingSrvClientErr, nil
	case "SysPowerSrvErr":
		return Err_SysPowerSrvErr, nil
	case "SysPowerSrvClientErr":
		return Err_SysPowerSrvClientErr, nil
	case "SysBlobSrvErr":
		return Err_SysBlobSrvErr, nil
	case "SysBlobSrvClientErr":
		return Err_SysBlobSrvClientErr, nil
	case "SysSiteSrvErr":
		return Err_SysSiteSrvErr, nil
	case "SysSiteSrvClientErr":
		return Err_SysSiteSrvClientErr, nil
	case "BuyCrmSrvErr":
		return Err_BuyCrmSrvErr, nil
	case "BuyCrmSrvClientErr":
		return Err_BuyCrmSrvClientErr, nil
	case "BuyOmsSrvErr":
		return Err_BuyOmsSrvErr, nil
	case "BuyOmsSrvClientErr":
		return Err_BuyOmsSrvClientErr, nil
	case "BuyPaySrvErr":
		return Err_BuyPaySrvErr, nil
	case "BuyPaySrvClientErr":
		return Err_BuyPaySrvClientErr, nil
	case "BuyPdmSrvErr":
		return Err_BuyPdmSrvErr, nil
	case "BuyPdmSrvClientErr":
		return Err_BuyPdmSrvClientErr, nil
	case "KitAigcSrvErr":
		return Err_KitAigcSrvErr, nil
	case "KitAigcSrvClientErr":
		return Err_KitAigcSrvClientErr, nil
	}
	return Err(0), fmt.Errorf("not a valid Err string")
}

func ErrPtr(v Err) *Err { return &v }
func (p *Err) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Err(result.Int64)
	return
}

func (p *Err) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
